enyo.kind({
    name: "findApps.TermsAndConditions",
    kind: enyo.VFlexBox,
    published:{

    },  
    
    components: [
			{name:"end-user", content: $L("HP webOS App Catalog End-User Terms And Conditions"), className: 'terms-text-subhead'},
			{content: $L("THE FOLLOWING TERMS AND CONDITIONS (“AGREEMENT”) APPLY TO YOUR USE OF THE HP WEBOS APP CATALOG (“APP CATALOG”), YOUR PURCHASE OF PRODUCTS (EACH, AN “APPLICATION”) THROUGH THE APP CATALOG, AND YOUR USE OF SUCH APPLICATIONS. BEFORE USING, DOWNLOADING FROM OR OTHERWISE ACCESSING THE HP APP CATALOG OR ANY APPLICATION, CAREFULLY READ THIS AGREEMENT. THE APPLICATIONS PROVIDED THROUGH THE APP CATALOG ARE LICENSED BY THE PROVIDER OF THE APPLICATION (“APPLICATION PROVIDER”) TO YOU, THE ORIGINAL END USER, SOLELY FOR YOUR PERSONAL USE AS SET FORTH BELOW AND SUBJECT TO THE APPLICABLE END-USER LICENSE AGREEMENT. IF YOU DO NOT AGREE TO THE TERMS AND CONDITIONS OF THIS AGREEMENT, DO NOT USE, DOWNLOAD OR OTHERWISE ACCESS THE APP CATALOG. USING, DOWNLOADING, OR OTHERWISE ACCESSING ANY PART OF THE APP CATALOG INDICATES THAT YOU ACCEPT THESE TERMS AND CONDITIONS.  YOU MUST BE AT LEAST 13 (THIRTEEN) YEARS OF AGE TO USE OR ACCESS THE APP CATALOG.  IF YOU ARE AT LEAST 13 BUT UNDER THE AGE OF 18, YOU MUST HAVE YOUR PARENT OR LEGAL GUARDIAN’S PERMISSION TO USE OR ACCESS THE APP CATALOG.")},
			{content: $L("PLEASE NOTE THAT IF YOU ARE A CONSUMER IN THE EUROPEAN ECONOMIC AREA OR SWITZERLAND, THIS LICENSE AGREEMENT DOES NOT AFFECT YOUR STATUTORY RIGHTS.  FOR FURTHER INFORMATION ABOUT YOUR STATUTORY RIGHTS CONTACT YOUR LOCAL AUTHORITY, TRADING STANDARDS DEPARTMENT OR CITIZENS ADVICE BUREAU (OR LOCAL EQUIVALENT)."), className: 'terms-text'},

			{name:"license-agreement", content: $L("Application License Agreement"), className: 'terms-text-subhead'},
			{content: $L("Your use of each Application that you download through the App Catalog is governed by the terms of the Application License Agreement between you and the Application Provider (the “Application License Agreement”) set forth below.  If the Application Provider provides an End-User License Agreement (“EULA”) with the Application, those terms shall supplement the Application License Agreement.  As between you and the Application Provider, any additional or different terms in such EULA shall take precedence over the terms in the Application License Agreement."), className: 'terms-text'},

			{name:"palm-role", content: $L("HP's Role In Providing Applications"), className: 'terms-text-subhead'},
			{content: $L("You agree that the license you purchase to each Application is a binding agreement between you and the Application Provider only. The Application Provider is solely responsible for that Application, the content therein, any terms, conditions and warranties to the extent that such terms, conditions and warranties have not been disclaimed, and any claims relating to that Application. You acknowledge that HP and HP’s subsidiaries are acting as agent for the Application Provider in providing each Application to you and is not a party to the license between you and the Application Provider. HP is not responsible for any Application, the content therein, or any terms, conditions, warranties or claims that you or any other party may have relating to that Application."), className: 'terms-text'},
			{content: $L("You further acknowledge and agree that HP is a third party beneficiary of the Application License Agreement and, any EULA, if so provided. You acknowledge and agree that HP will have the right (and will be deemed to have accepted the right) to enforce such license against you as a third party beneficiary of those agreements."), className: 'terms-text'},

			{name:"restrictions", content: $L("Restrictions"), className: 'terms-text-subhead'},
			{content: $L("You agree that HP and/or third parties own all right, title and interest in and to the App Catalog and all Applications (including all copyrights and trademarks relating thereto). Each Application is licensed for use only for a single HP webOS account, and you may not distribute or make the Application available over a network or for use with multiple devices. Except as otherwise provided below, you may not modify or alter the Application in any way, and may only use the Application as expressly set forth above and as set forth in the applicable EULA for the Application. You agree that you will not attempt to, or assist or encourage any other person or entity to circumvent, disable or modify any security technology or software that is part of the Application or is used on your HP device. Except as set forth above, HP and the Application Providers reserve all other rights in or to the Application. If applicable law permits you to copy or modify the Application, then you may copy and modify the Application solely to the extent, and for such purposes as, expressly permitted by applicable law. You agree that you will not engage in any activity that interferes with or disrupts the App Catalog or services available through Applications you have downloaded. You further agree that you will not use any Applications you download to interfere with or otherwise disrupt any servers, networks, websites or services."), className: 'terms-text'},

			{name:"right-to-modify", content: $L("HP Has The Right To Modify, Change or Terminate Your Use Of The App Catalog or Applications Found in the App Catalog"), className: 'terms-text-subhead'},
			{content: $L("HP reserves the right, at its sole discretion and at any time, to add, remove, disable access to, block, or modify the App Catalog, and to add, remove, disable access to, block, or modify remotely any Applications previously downloaded to your device from the App Catalog. HP may be required to take these actions due to changes in the obligations or restrictions from its third party licensors or partners, an Application Provider’s serious violation of its agreement with HP, or due to any governmental restriction or court order. HP may also impose limits on the use of or access to certain features or portions of the App Catalog or Applications downloaded from the App Catalog, in any case and without notice or liability. If HP removes, disables access to, or otherwise blocks you from accessing an Application, you will need to contact the Application Provider for further action."), className: 'terms-text'},

			{name:"modify-terms", content: $L("HP Has The Right To Modify These Terms"), className: 'terms-text-subhead'},
			{content: $L("HP reserves the right to modify the terms of this Agreement at its sole discretion at any time. Any such modification will be effective upon HP notifying you prior to your continued use or access of the App Catalog. Your continued use of the App Catalog after such notice will constitute your binding acceptance of the Agreement as revised."), className: 'terms-text'},

			{name:"fees", content: $L("Fees And Payment"), className: 'terms-text-subhead'},
			{content: $L("Applications are either available for download at no charge or, where available, require payment of a specified amount by the end-user (“Paid-For Applications”).  For Paid-For Applications, the App Catalog accepts credit cards and Mastercard or Visa branded debit cards (each, a “Card”).  You agree to pay for all Paid-For Applications you purchase."), className: 'terms-text'},  
            {content: $L("YOU ARE RESPONSIBLE FOR THE TIMELY PAYMENT OF ALL FEES AND FOR PROVIDING HP OR ITS DESIGNEE WITH A VALID CARD FOR PAYMENT OF ALL FEES."), className: 'terms-text'}, 
			{content: $L("You will be required to provide accurate, current and complete Card information before you will be permitted to download Paid-For Applications. You authorize HP or its agents to charge or debit your Card the specified amount plus any applicable sales tax for each Paid-For Application you download. Once you enter a Card, such Card will be used for future transactions unless you designate a different Card. Debit cards and check cards have daily spending limits that may prevent the processing of your order. If the transaction is not accepted online, you will be unable to use that Card for your transaction and should use another Card."), className: 'terms-text'},
			{content: $L("Alternatively, in some locations with some wireless carriers, you may elect to be billed by the wireless carrier providing telecommunications service for your device. If so enabled and you choose wireless carrier billing, the related terms and conditions of your wireless carrier will apply."), className: 'terms-text'},

			{name:"prices", content: $L("Prices"), className: 'terms-text-subhead'},
			{content: $L("Your total price will include the price of the Application plus any applicable sales tax, value added tax or other applicable taxes. Prices in the European Union are inclusive of taxes. Sales tax in the United States will be based on the billing address and the sales tax rate in effect at the time your transaction is completed. For international customers, other transaction taxes may apply. Tax exemptions will not be processed for App Catalog purchases. HP reserves the right to change prices for Applications offered through the App Catalog at any time, and does not provide price protection or refunds in the event of a temporary or permanent price drop, rebate or other promotion."), className: 'terms-text'},

			{name:"refunds", content: $L("Refunds"), className: 'terms-text-subhead'},
			{content: $L("Prices and availability of any Applications are subject to change at any time.   All sales of successfully downloaded Applications are final and non-refundable."), className: 'terms-text'},

			{name:"delivery", content: $L("Delivery Of Applications"), className: 'terms-text-subhead'},
			{content: $L("If delivery of an Application you purchased is interrupted, you will be able to resume or restart such delivery at no additional charge. On occasion, technical problems may delay or prevent delivery of an Application. Your exclusive and sole remedy with respect to such Application that is not delivered within a reasonable period will be replacement of such Application, or refund of the price paid for such Application if such Application is no longer available for download. "), className: 'terms-text'},

			{name:"customer-service", content: $L("Customer Service"), className: 'terms-text-subhead'},
			{content: $L("For any issues or questions concerning the App Catalog, please go to www.palm.com and click on the “Support” link. HP does not provide support for Applications, and the Application Provider is responsible for providing such support. For any issues or questions concerning specific Applications, please contact the Application Provider."), className: 'terms-text'},

			{name:"responsibility", content: $L("Responsibility For App Catalog Activities"), className: 'terms-text-subhead'},
			{content: $L("You are entirely responsible for all activities that occur on or through the App Catalog from your device, including any unauthorized purchases made through your device, and you agree to notify HP immediately of any unauthorized use of your device or any other breach of security. HP is not responsible for any losses arising out of the unauthorized use of your device. HP reserves the right to disable, block, suspend or otherwise limit your access to the App Catalog in the event of unauthorized use of your device or if you violate the terms of this Agreement."), className: 'terms-text'},

			{name:"content-accessed", content: $L("Content Accessed Through Applications"), className: 'terms-text-subhead'},
			{content: $L("You acknowledge and agree that certain Applications may provide access to products, services, web content or other third-party materials (together, “Third-Party Content”) and that HP is not responsible for such Third-Party Content. HP makes no representations or warranties regarding, and accepts no liability in respect of, such Third-Party Content. You further acknowledge that by accessing the App Catalog or Applications downloaded through the App Catalog, you may be exposed to Third-Party Content that contains explicit language or is offensive, indecent or objectionable to you, and that you may not be warned about the specific Application or Third-Party Content in advance. You agree that your downloading and use of all Applications will be at your sole risk, and HP shall have no liability to you as a result of any exposure through such Applications."), className: 'terms-text'},

			{name:"internet", content: $L("Internet Connection"), className: 'terms-text-subhead'},
			{content: $L("Access to and downloading from the App Catalog requires an internet connection.  In addition, your use of certain Applications may require an internet connection. "), className: 'terms-text'},

			{name:"reviews", content: $L("Reviews"), className: 'terms-text-subhead'},
			{content:$L("HP, in its sole discretion, may permit users to post reviews of Applications on the App Catalog. Such reviews reflect the opinions of the reviewers and not HP, and HP makes no representations or warranties as to the accuracy or completeness of the reviews. You agree that HP shall have no liability to you if you rely on the reviews to download or use an Application.  HP reserves the right to, but has no obligation to, remove reviews that HP deems irrelevant or otherwise inappropriate for any reason. If you post a review, you hereby grant HP a perpetual, worldwide, fully transferable and sub-licensable, irrevocable, royalty-free license to make, use, sell, market, reproduce, create derivative works of, distribute, perform, and display the review in any manner and for any purpose. You acknowledge that your personally identifiable information may be associated with your review unless you post the review anonymously. If you post a review, you agree not to post, publish or transmit any material that: (i) is false or misleading; (ii) is defamatory; (iii) invades another’s privacy; (iv) is obscene, pornographic, or offensive; (v) promotes bigotry, racism, hatred or harm against any individual or group; (vi) infringes on another’s rights, including but not limited to any intellectual property rights; or (vii) violates, or encourages any conduct that would violate any applicable law or regulation or would give rise to civil liability."), className: 'terms-text'},

			{name:"consent-use", content: $L("Consent To Use Of Data"), className: 'terms-text-subhead'},
			{content:$L("You agree that HP, its affiliates and designated agents may collect and use technical and related information, gathered in any manner, as part of product support services related to the App Catalog. This includes the use of Google Analytics or other analytics tools for the collection of anonymous usage information, which helps HP understand how visitors engage with the application catalog. HP, its affiliates and designated agents may use this information solely to improve its products or to provide customized services or technologies to you. HP will collect and use this information in accordance with its privacy policy (http://www.palm.com/privacy) and in accordance with applicable data protection laws. HP, its affiliates and designated agents may disclose this information to others, but not in a form that personally identifies you."), className: 'terms-text'},

			{name:"reverse-engineering", content: $L("Reverse Engineering"), className: 'terms-text-subhead'},
			{content:$L("You may not reverse engineer, decompile, or disassemble the App Catalog or any Applications downloaded from the App Catalog, except and only to the extent that such activity is expressly permitted by applicable law."), className: 'terms-text'},

			{name:"indemnification", content: $L("Indemnification"), className: 'terms-text-subhead'},
			{content:$L("To the maximum extent permitted by law, you agree to defend, indemnify and hold HP, its directors, officers, employees, affiliates, and agents harmless from and against any and all claims arising out of your breach of this Agreement, your use of the App Catalog, or your use of any Applications downloaded from the App Catalog."), className: 'terms-text'},

			{name:"warranty", content: $L("Warranty And Disclaimers"), className: 'terms-text-subhead'},
			{content: $L("EXCEPT AS MAY BE PROVIDED UNDER A WARRANTY FOR NEWLY PURCHASED DEVICES, AND TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT USE OF THE APP CATALOG IS AT YOUR SOLE RISK AND THAT ACCESS TO THE APP CATALOG IS PROVIDED TO YOU ON AN “AS IS” AND “AS AVAILABLE” BASIS AND WITHOUT ANY WARRANTY OF ANY KIND OR NATURE. HP DOES NOT WARRANT THAT USE OF THE APP CATALOG WILL BE UNINTERRUPTED, FAULT-TOLERANT OR ERROR FREE. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, HP AND ITS SUPPLIERS EXPRESSLY DISCLAIM ANY IMPLIED OR STATUTORY TERMS, CONDITIONS OR WARRANTIES, INCLUDING THOSE AS TO MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, ACCURACY, CORRESPONDENCE WITH DESCRIPTION, SATISFACTORY QUALITY AND NON-INFRINGEMENT. HP MAKES NO WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, WITH REGARD TO ANY THIRD PARTY SOFTWARE OR OPEN SOURCE SOFTWARE. ALL THIRD PARTY SOFTWARE AND OPEN SOURCE SOFTWARE IS PROVIDED “AS-IS”, WITHOUT WARRANTIES OF ANY KIND BY HP."), className: 'terms-text'},

			{name:"liability", content: $L("Limitation Of Liability"), className: 'terms-text-subhead'},
			{content: $L("NOTHING IN THIS LIMITATION OF LIABILITY LIMITS OR EXCLUDES HP’S OR ITS SUPPLIERS’ LIABILITY FOR DEATH OR PERSONAL INJURY CAUSED BY NEGLIGENCE, FOR REPRESENTATIONS MADE FRAUDULENTLY, OR FOR ANY OTHER LIABILITY WHICH CANNOT BE LIMITED OR EXCLUDED BY APPLICABLE LAW. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, NEITHER HP NOR ITS SUPPLIERS SHALL BE LIABLE FOR INCIDENTAL, CONSEQUENTIAL, INDIRECT, SPECIAL, OR PUNITIVE DAMAGES OF ANY KIND, LOSS OF INFORMATION OR DATA, LOSS OF REVENUE, LOSS OF BUSINESS OR OTHER FINANCIAL LOSS ARISING OUT OF OR IN CONNECTION WITH THE LICENSE OR USE OF THE APP CATALOG OR APPLICATIONS DOWNLOADED FROM THE APP CATALOG, WHETHER BASED IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT PRODUCT LIABILITY OR ANY OTHER THEORY, EVEN IF HP HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND EVEN IF ANY LIMITED REMEDY IS DEEMED TO HAVE FAILED OF ITS ESSENTIAL PURPOSE. HP’S ENTIRE LIABILITY SHALL BE LIMITED TO REPLACEMENT, REPAIR, OR REFUND OF THE PURCHASE PRICE PAID FOR THE APPLICABLE APPLICATION, AT HP’S OPTION. IN NO EVENT WILL HP BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, PUNITIVE, EXEMPLARY, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF ANY APPLICATION OR OPEN SOURCE SOFTWARE, EVEN IF HP HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR LOSSES."), className: 'terms-text'},
            {content: $L("Some jurisdictions do not allow the exclusion or limitation of implied warranties, terms or conditions or the limitation of incidental or consequential damages so the above limitations and exclusions may be limited in their application to you. For further information about your statutory rights, please contact your local authority, trading standards department, citizens’ advice bureau or equivalent.")},

			{name:"export", content: $L("Export Restrictions"), className: 'terms-text-subhead'},
			{content:$L("You agree that you will not export or re-export any Application or accompanying documentation (or any copies thereof) in violation of any applicable laws or regulations of the United States. You agree to comply with all applicable United States and international export laws and regulations. These laws include restrictions on destinations, end users, and end use.  You represent and warrant that you are not prohibited from receiving exports or services under United States or other applicable export laws."), className: 'terms-text'},

			{name:"terms-termination", content: $L("Term And Termination"), className: 'terms-text-subhead'},
			{content:$L("This Agreement is effective until terminated. HP may terminate this Agreement in whole or as it applies to your use of any Application if you breach any of the terms of this Agreement. You may terminate it at any time by ceasing to use the App Catalog, provided that any terms relating to your use of each Application will survive unless and until you destroy all copies of such Application and related documentation. Some jurisdictions do not allow the termination of this type of Agreement, so the above provision may be limited in its application to you. In addition, HP reserves the right to modify, suspend, or discontinue the App Catalog (or any part or content thereof) at any time with or without notice to you, and HP will not be liable to you or to any third party should it exercise such rights. HP may freely assign this Agreement to any subsidiary or affiliate of HP without Your approval."), className: 'terms-text'},

			{name:"special-rights", content: $L("Special Rights For The License Or Use By The U.S. Government"), className: 'terms-text-subhead'},
			{content:$L("If an Application is being used by or licensed to the United States Government, the following shall apply: The Application licensed under this Agreement is “commercial computer software” as the term is described in 48 C.F.R. 252.227-7014(a)(1). If acquired by or on behalf of a civilian agency, the U.S. Government acquires this commercial computer software and/or commercial computer software documentation subject to the terms of this Agreement as specified in 48 C.F.R. 12.212 (Computer Software) and 48 C.F.R. 12.211 (Technical Data) of the Federal Acquisition Regulations (“FAR”) and its successors. If acquired by or on behalf of any agency within the Department of Defense (“DOD”), the U.S. Government acquires this commercial computer software and/ or commercial computer software documentation subject to the terms of this Agreement as specified in 48 C.F.R. 227.7202-3 of the DOD FAR Supplement (“DFAR”) and its successors."), className: 'terms-text'},

			{name:"governing-law", content: $L("Governing Law"), className: 'terms-text-subhead'},
			{content:$L("This Agreement shall be governed by the laws of the State of California and by the federal laws of the United States, excluding their conflicts of laws provisions. The United Nations Convention on Contracts for the International Sale of Goods (1980) is hereby excluded in its entirety from application to this Agreement. If you are a consumer residing in the European Economic Area or Switzerland, this Agreement shall be governed by the law of the country in which you reside. "), className: 'terms-text'},

			{name:"severability", content: $L("Severability"), className: 'terms-text-subhead'},
			{content:$L("In the event any provision of this Agreement is found to be invalid, illegal or unenforceable, the validity, legality and enforceability of any of the remaining provisions shall not in any way be affected or impaired."), className: 'terms-text'},

			{name:"enforcement", content: $L("Enforcement Of Agreement"), className: 'terms-text-subhead'},
			{content:$L("HP reserves the right to takes any steps it believes to be reasonably necessary or appropriate to enforce and/or verify compliance with any part of this Agreement. You agree that HP has the right, without liability to you, to disclose any information relating to your use of the App Catalog to law enforcement authorities, government officials, and/or a third party, as HP believes is reasonably necessary or appropriate to enforce and/or verify compliance with any part of this Agreement."), className: 'terms-text'},

			{name:"entire-agreement", content: $L("Entire Agreement"), className: 'terms-text-subhead'},
			{content:$L("By accepting this Agreement, you agree that the Agreement (including all incorporated or referenced documents) set forth the entire agreement between you and HP, and supersede all prior agreements, whether written or oral, with respect to the App Catalog and all Applications, notwithstanding the terms or conditions of any such prior agreements. If HP fails to enforce any right or provision in this Agreement, such failure will not constitute a waiver of such right or provision."), className: 'terms-text'},
			{content:$L("Hewlett-Packard Company")},
			{content:$L("950 W. Maude Ave.")},
			{content:$L("Sunnyvale CA 94085-2801")},
			{content:$L("United States of America")},
			{content:$L("www.hp.com")},
			{content:$L("Last updated: March 15, 2011"), style: 'margin-bottom:10px'},
		
			{name:"app-license-agreement", content: $L("Application License Agreement"), className: 'terms-text-subhead'},
			{content:$L("THE FOLLOWING TERMS AND CONDITIONS APPLY TO YOUR USE OF EACH APPLICATION YOU DOWNLOAD FROM THE APP CATALOG (EACH, AN “APPLICATION”).  BEFORE USING ANY APPLICATION, CAREFULLY READ THIS AGREEMENT"), className: 'terms-text'},
			{content:$L("PLEASE NOTE THAT IF YOU ARE A CONSUMER IN THE EUROPEAN ECONOMIC AREA OR SWITZERLAND, THIS LICENSE AGREEMENT DOES NOT AFFECT YOUR STATUTORY RIGHTS.  FOR FURTHER INFORMATION ABOUT YOUR STATUTORY RIGHTS CONTACT YOUR LOCAL AUTHORITY, TRADING STANDARDS DEPARTMENT OR CITIZENS ADVICE BUREAU (OR LOCAL EQUIVALENT)."), className: 'terms-text'},
			{content:$L("The license granted hereunder is granted to you by the provider of the Application (“Application Provider”) and not by Hewlett-Packard Company  (“HP”). If the Application Provider provides an End User License Agreement (“EULA”) with the Application, those terms shall supplement this Application License Agreement.  As between you and the Application Provider, any additional or different terms in such EULA shall take precedence over the terms in this Application License Agreement."), className: 'terms-text'}, 
			{content:$L("You acknowledge and agree that HP is a third party beneficiary of this Application License Agreement and any EULA, if so provided. You acknowledge and agree that HP will have the right (and will be deemed to have accepted the right) to enforce such license against you as a third party beneficiary of those agreements."), className: 'terms-text'},

			{name:"app-license-grant", content: $L("License Grant"), className: 'terms-text-subhead'},
			{content:$L("You are hereby granted a limited, non-transferable license to use the Application for a single HP account that you control and solely for devices operating on webOS. You may not rent, lease, lend, sell, redistribute or sublicense the Application. You may not reverse engineer, decompile, or disassemble the Application, except and only to the extent that such activity is expressly permitted by applicable law. Any attempt to do so is a violation of the rights of the Application Provider. If you breach this restriction, you may be subject to prosecution and damages. The terms of the license will govern any upgrades provided by the Application Provider that replace and/or supplement the original Application, unless such upgrade is accompanied by a separate license in which case the terms of that license will govern. The Application Provider reserves all rights in and to the Application not expressly granted to you under this Application License Agreement."), className: 'terms-text'},

			{name:"app-consent-use", content: $L("Consent To Use Of Data"), className: 'terms-text-subhead'},
			{content:$L("You agree that the Application Provider may collect and use technical and related information, gathered in any manner, as part of product support services related to the Application. The Application Provider may use this information solely to improve its products or to provide customized services or technologies to you.  The Application Provider may disclose this information to others, but not in a form that personally identifies you.")},

			{name:"app-no-warranty", content: $L("No Warranty"), className: 'terms-text-subhead'},
			{content: $L("YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT USE OF THE APPLICATION IS AT YOUR SOLE RISK AND THAT ACCESS TO THE APPLICATION IS PROVIDED TO YOU ON AN “AS IS” AND “AS AVAILABLE” BASIS AND WITHOUT ANY WARRANTY OF ANY KIND OR NATURE. THE APPLICATION PROVIDER DOES NOT WARRANT THAT USE OF THE APPLICATION WILL BE UNINTERRUPTED, FAULT-TOLERANT OR ERROR FREE.  TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE APPLICATION PROVIDER EXPRESSLY DISCLAIMS ANY IMPLIED OR STATUTORY TERMS, CONDITIONS OR WARRANTIES, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, ACCURACY, CORRESPONDENCE WITH DESCRIPTION, SATISFACTORY QUALITY AND NON-INFRINGEMENT.  THE APPLICATION PROVIDER MAKES NO WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, WITH REGARD TO ANY THIRD PARTY SOFTWARE OR OPEN SOURCE SOFTWARE.  "), className: 'terms-text'},

			{name:"app-limitation-liability", content: $L("Limitation Of Liability"), className: 'terms-text-subhead'},
			{content:$L("NOTHING IN THIS LIMITATION OF LIABILITY LIMITS OR EXCLUDES THE APPLICATION PROVIDER’S LIABILITY FOR DEATH OR PERSONAL INJURY CAUSED BY NEGLIGENCE, FOR REPRESENTATIONS MADE FRAUDULENTLY, OR FOR ANY OTHER LIABILITY WHICH CANNOT BE LIMITED OR EXCLUDED BY APPLICABLE LAW. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE APPLICATION PROVIDER SHALL NOT BE LIABLE FOR INCIDENTAL, CONSEQUENTIAL, INDIRECT, SPECIAL, OR PUNITIVE DAMAGES OF ANY KIND, LOSS OF INFORMATION OR DATA, LOSS OF REVENUE, LOSS OF BUSINESS OR OTHER FINANCIAL LOSS ARISING OUT OF OR IN CONNECTION WITH THE LICENSE OR USE OF THE APPLICATION, WHETHER BASED IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT PRODUCT LIABILITY OR ANY OTHER THEORY, EVEN IF THE APPLICATION PROVIDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND EVEN IF ANY LIMITED REMEDY IS DEEMED TO HAVE FAILED OF ITS ESSENTIAL PURPOSE. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE APPLICATION PROVIDER’S ENTIRE LIABILITY SHALL BE LIMITED TO REPLACEMENT, REPAIR, OR REFUND OF THE PURCHASE PRICE PAID FOR THE APPLICATION, AT THE APPLICATION PROVIDER’S OPTION.  IN NO EVENT WILL THE APPLICATION PROVIDER BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, PUNITIVE, EXEMPLARY, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF ANY THIRD PARTY SOFTWARE OR OPEN SOURCE SOFTWARE, EVEN IF THE APPLICATION PROVIDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR LOSSES."), className: 'terms-text'},
			{content:$L("Some jurisdictions do not allow the exclusion or limitation of implied warranties or the limitation of incidental or consequential damages so the above limitations and exclusions may be limited in their application to you. "), className: 'terms-text'},

			{name:"app-export-restrictions", content: $L("Export Restrictions"), className: 'terms-text-subhead'},
			{content:$L("You agree that you will not export or re-export the Application or accompanying documentation (or any copies thereof) in violation of any applicable laws or regulations of the United States.  You agree to comply with all applicable United States and international export laws and regulations. These laws include restrictions on destinations, end users, and end use.  You represent and warrant that you are not prohibited from receiving exports or services under United States or other applicable export laws."), className: 'terms-text'},

			{name:"app-terms-termination", content: $L("Term And Termination"), className: 'terms-text-subhead'},
			{content:$L("The license is effective until terminated by you or the Application Provider. Your rights under this license will terminate automatically without notice from the Application Provider if you fail to comply with any term(s) of this license. Upon termination of the license, you shall cease all use of the Application, and destroy all copies, full or partial, of the Application, including any accompanying documentation."), className: 'terms-text'},

			{name:"app-special-rights", content: $L("Special Rights For The License Or Use By The U.S. Government"), className: 'terms-text-subhead'},
			{content: $L(" If the Application is being used by or licensed to the United States Government, the following shall apply: The Application licensed under this Application License Agreement is “commercial computer software” as the term is described in 48 C.F.R. 252.227-7014(a)(1). If acquired by or on behalf of a civilian agency, the U.S. Government acquires this commercial computer software and/or commercial computer software documentation subject to the terms of this Agreement as specified in 48 C.F.R. 12.212 (Computer Software) and 48 C.F.R. 12.211 (Technical Data) of the Federal Acquisition Regulations (“FAR”) and its successors. If acquired by or on behalf of any agency within the Department of Defense (“DOD”), the U.S. Government acquires this commercial computer software and/ or commercial computer software documentation subject to the terms of this Application License Agreement as specified in 48 C.F.R. 227.7202-3 of the DOD FAR Supplement (“DFAR”) and its successors."), className: 'terms-text'},

			{name:"app-governing-law", content: $L("Governing Law"), className: 'terms-text-subhead'},
			{content:$L("This Application License Agreement shall be governed by the laws of the State of California and by the federal laws of the United States, excluding their conflicts of laws provisions. The United Nations Convention on Contracts for the International Sale of Goods (1980) is hereby excluded in its entirety from application to this Application License Agreement. If you acquired the Application in the European Economic Area or Switzerland, this Agreement shall be governed by the law of the country in which you purchased the Application."), className: 'terms-text'},

			{name:"app-severability", content: $L("Severability"), className: 'terms-text-subhead'},
			{content:$L("In the event any provision of this Application License Agreement is found to be invalid, illegal or unenforceable, the validity, legality and enforceability of any of the remaining provisions shall not in any way be affected or impaired. "), className: 'terms-text'},

			{name:"app-entire-agreement", content: $L("Entire Agreement"), className: 'terms-text-subhead'},
			{content:$L("By accepting this Application License Agreement, you agree that such agreement (including all incorporated or referenced documents) sets forth the entire agreement between you and the Application Provider, and supersedes all prior agreements, whether written or oral, with respect to the Application, notwithstanding the terms or conditions of any such prior agreements.  If the Application Provider fails to enforce any right or provision in this Application License Agreement, such failure will not constitute a waiver of such right or provision."), className: 'terms-text'},

			{name:"update-date", content: $L("Last updated: March 15, 2011"), className: 'terms-text'}
    ]
});
