/* LOCALIZATION USE ONLY. DO NOT LOAD VIA depends.js */
var response = {
    "statusCode": "OK",
    "headers": {},
    "body": {
        "info": {},
        "stats": {},
        "error": "",
        "errorDetails": "",
        "response": {
            "countries": [{
                "id": 35,
                "code": "AF",
                "name": $L("AFGHANISTAN")
            }, {
                "id": 239,
                "code": "AX",
                "name": $L("ÅLAND ISLANDS")
            }, {
                "id": 38,
                "code": "AL",
                "name": $L("ALBANIA")
            }, {
                "id": 82,
                "code": "DZ",
                "name": $L("ALGERIA")
            }, {
                "id": 44,
                "code": "AS",
                "name": $L("AMERICAN SAMOA")
            }, {
                "id": 33,
                "code": "AD",
                "name": $L("ANDORRA")
            }, {
                "id": 41,
                "code": "AO",
                "name": $L("ANGOLA")
            }, {
                "id": 37,
                "code": "AI",
                "name": $L("ANGUILLA")
            }, {
                "id": 42,
                "code": "AQ",
                "name": $L("ANTARCTICA")
            }, {
                "id": 36,
                "code": "AG",
                "name": $L("ANTIGUA AND BARBUDA")
            }, {
                "id": 43,
                "code": "AR",
                "name": $L("ARGENTINA")
            }, {
                "id": 39,
                "code": "AM",
                "name": $L("ARMENIA")
            }, {
                "id": 45,
                "code": "AW",
                "name": $L("ARUBA")
            }, {
                "id": 245,
                "code": "AU",
                "name": $L("AUSTRALIA")
            }, {
                "id": 1,
                "code": "AT",
                "name": $L("AUSTRIA")
            }, {
                "id": 46,
                "code": "AZ",
                "name": $L("AZERBAIJAN")
            }, {
                "id": 58,
                "code": "BS",
                "name": $L("BAHAMAS")
            }, {
                "id": 52,
                "code": "BH",
                "name": $L("BAHRAIN")
            }, {
                "id": 49,
                "code": "BD",
                "name": $L("BANGLADESH")
            }, {
                "id": 48,
                "code": "BB",
                "name": $L("BARBADOS")
            }, {
                "id": 62,
                "code": "BY",
                "name": $L("BELARUS")
            }, {
                "id": 2,
                "code": "BE",
                "name": $L("BELGIUM")
            }, {
                "id": 63,
                "code": "BZ",
                "name": $L("BELIZE")
            }, {
                "id": 54,
                "code": "BJ",
                "name": $L("BENIN")
            }, {
                "id": 55,
                "code": "BM",
                "name": $L("BERMUDA")
            }, {
                "id": 59,
                "code": "BT",
                "name": $L("BHUTAN")
            }, {
                "id": 57,
                "code": "BO",
                "name": $L("BOLIVIA")
            }, {
                "id": 47,
                "code": "BA",
                "name": $L("BOSNIA AND HERZEGOVINA")
            }, {
                "id": 61,
                "code": "BW",
                "name": $L("BOTSWANA")
            }, {
                "id": 60,
                "code": "BV",
                "name": $L("BOUVET ISLAND")
            }, {
                "id": 3,
                "code": "BR",
                "name": $L("BRAZIL")
            }, {
                "id": 117,
                "code": "IO",
                "name": $L("BRITISH INDIAN OCEAN TERRITORY")
            }, {
                "id": 227,
                "code": "VG",
                "name": $L("BRITISH VIRGIN ISLANDS")
            }, {
                "id": 56,
                "code": "BN",
                "name": $L("BRUNEI DARUSSALAM")
            }, {
                "id": 51,
                "code": "BG",
                "name": $L("BULGARIA")
            }, {
                "id": 50,
                "code": "BF",
                "name": $L("BURKINA FASO")
            }, {
                "id": 53,
                "code": "BI",
                "name": $L("BURUNDI")
            }, {
                "id": 124,
                "code": "KH",
                "name": $L("CAMBODIA")
            }, {
                "id": 71,
                "code": "CM",
                "name": $L("CAMEROON")
            }, {
                "id": 4,
                "code": "CA",
                "name": $L("CANADA")
            }, {
                "id": 75,
                "code": "CV",
                "name": $L("CAPE VERDE")
            }, {
                "id": 130,
                "code": "KY",
                "name": $L("CAYMAN ISLANDS")
            }, {
                "id": 66,
                "code": "CF",
                "name": $L("CENTRAL AFRICAN REPUBLIC")
            }, {
                "id": 206,
                "code": "TD",
                "name": $L("CHAD")
            }, {
                "id": 70,
                "code": "CL",
                "name": $L("CHILE")
            }, {
                "id": 28,
                "code": "CN",
                "name": $L("CHINA")
            }, {
                "id": 76,
                "code": "CX",
                "name": $L("CHRISTMAS ISLAND")
            }, {
                "id": 64,
                "code": "CC",
                "name": $L("COCOS (KEELING) ISLANDS")
            }, {
                "id": 72,
                "code": "CO",
                "name": $L("COLOMBIA")
            }, {
                "id": 126,
                "code": "KM",
                "name": $L("COMOROS")
            }, {
                "id": 67,
                "code": "CG",
                "name": $L("CONGO")
            }, {
                "id": 69,
                "code": "CK",
                "name": $L("COOK ISLANDS")
            }, {
                "id": 73,
                "code": "CR",
                "name": $L("COSTA RICA")
            }, {
                "id": 68,
                "code": "CI",
                "name": $L("COTE D'IVOIRE")
            }, {
                "id": 113,
                "code": "HR",
                "name": $L("CROATIA")
            }, {
                "id": 74,
                "code": "CU",
                "name": $L("CUBA")
            }, {
                "id": 77,
                "code": "CY",
                "name": $L("CYPRUS")
            }, {
                "id": 78,
                "code": "CZ",
                "name": $L("CZECH REPUBLIC")
            }, {
                "id": 128,
                "code": "KP",
                "name": $L("DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA")
            }, {
                "id": 5,
                "code": "DK",
                "name": $L("DENMARK")
            }, {
                "id": 79,
                "code": "DJ",
                "name": $L("DJIBOUTI")
            }, {
                "id": 80,
                "code": "DM",
                "name": $L("DOMINICA")
            }, {
                "id": 81,
                "code": "DO",
                "name": $L("DOMINICAN REPUBLIC")
            }, {
                "id": 83,
                "code": "EC",
                "name": $L("ECUADOR")
            }, {
                "id": 85,
                "code": "EG",
                "name": $L("EGYPT")
            }, {
                "id": 202,
                "code": "SV",
                "name": $L("EL SALVADOR")
            }, {
                "id": 104,
                "code": "GQ",
                "name": $L("EQUATORIAL GUINEA")
            }, {
                "id": 87,
                "code": "ER",
                "name": $L("ERITREA")
            }, {
                "id": 84,
                "code": "EE",
                "name": $L("ESTONIA")
            }, {
                "id": 88,
                "code": "ET",
                "name": $L("ETHIOPIA")
            }, {
                "id": 90,
                "code": "FK",
                "name": $L("FALKLAND ISLANDS (MALVINAS)")
            }, {
                "id": 92,
                "code": "FO",
                "name": $L("FAROE ISLANDS")
            }, {
                "id": 91,
                "code": "FM",
                "name": $L("FEDERATED STATES OF MICRONESIA")
            }, {
                "id": 89,
                "code": "FJ",
                "name": $L("FIJI")
            }, {
                "id": 6,
                "code": "FI",
                "name": $L("FINLAND")
            }, {
                "id": 7,
                "code": "FR",
                "name": $L("FRANCE")
            }, {
                "id": 96,
                "code": "GF",
                "name": $L("FRENCH GUIANA")
            }, {
                "id": 173,
                "code": "PF",
                "name": $L("FRENCH POLYNESIA")
            }, {
                "id": 207,
                "code": "TF",
                "name": $L("FRENCH SOUTHERN TERRITORIES")
            }, {
                "id": 93,
                "code": "GA",
                "name": $L("GABON")
            }, {
                "id": 101,
                "code": "GM",
                "name": $L("GAMBIA")
            }, {
                "id": 95,
                "code": "GE",
                "name": $L("GEORGIA")
            }, {
                "id": 8,
                "code": "DE",
                "name": $L("GERMANY")
            }, {
                "id": 98,
                "code": "GH",
                "name": $L("GHANA")
            }, {
                "id": 99,
                "code": "GI",
                "name": $L("GIBRALTAR")
            }, {
                "id": 105,
                "code": "GR",
                "name": $L("GREECE")
            }, {
                "id": 100,
                "code": "GL",
                "name": $L("GREENLAND")
            }, {
                "id": 94,
                "code": "GD",
                "name": $L("GRENADA")
            }, {
                "id": 103,
                "code": "GP",
                "name": $L("GUADELOUPE")
            }, {
                "id": 108,
                "code": "GU",
                "name": $L("GUAM")
            }, {
                "id": 107,
                "code": "GT",
                "name": $L("GUATEMALA")
            }, {
                "id": 97,
                "code": "GG",
                "name": $L("GUERNSEY")
            }, {
                "id": 102,
                "code": "GN",
                "name": $L("GUINEA")
            }, {
                "id": 109,
                "code": "GW",
                "name": $L("GUINEA-BISSAU")
            }, {
                "id": 110,
                "code": "GY",
                "name": $L("GUYANA")
            }, {
                "id": 114,
                "code": "HT",
                "name": $L("HAITI")
            }, {
                "id": 111,
                "code": "HM",
                "name": $L("HEARD ISLAND AND MCDONALD ISLANDS")
            }, {
                "id": 224,
                "code": "VA",
                "name": $L("HOLY SEE (VATICAN CITY STATE)")
            }, {
                "id": 112,
                "code": "HN",
                "name": $L("HONDURAS")
            }, {
                "id": 9,
                "code": "HK",
                "name": $L("HONG KONG")
            }, {
                "id": 115,
                "code": "HU",
                "name": $L("HUNGARY")
            }, {
                "id": 10,
                "code": "IS",
                "name": $L("ICELAND")
            }, {
                "id": 24,
                "code": "IN",
                "name": $L("INDIA")
            }, {
                "id": 25,
                "code": "ID",
                "name": $L("INDONESIA")
            }, {
                "id": 118,
                "code": "IQ",
                "name": $L("IRAQ")
            }, {
                "id": 11,
                "code": "IE",
                "name": $L("IRELAND")
            }, {
                "id": 119,
                "code": "IR",
                "name": $L("ISLAMIC REPUBLIC OF IRAN")
            }, {
                "id": 240,
                "code": "IM",
                "name": $L("ISLE OF MAN")
            }, {
                "id": 116,
                "code": "IL",
                "name": $L("ISRAEL")
            }, {
                "id": 12,
                "code": "IT",
                "name": $L("ITALY")
            }, {
                "id": 120,
                "code": "JM",
                "name": $L("JAMAICA")
            }, {
                "id": 13,
                "code": "JP",
                "name": $L("JAPAN")
            }, {
                "id": 241,
                "code": "JE",
                "name": $L("JERSEY")
            }, {
                "id": 121,
                "code": "JO",
                "name": $L("JORDAN")
            }, {
                "id": 131,
                "code": "KZ",
                "name": $L("KAZAKHSTAN")
            }, {
                "id": 122,
                "code": "KE",
                "name": $L("KENYA")
            }, {
                "id": 125,
                "code": "KI",
                "name": $L("KIRIBATI")
            }, {
                "id": 129,
                "code": "KW",
                "name": $L("KUWAIT")
            }, {
                "id": 123,
                "code": "KG",
                "name": $L("KYRGYZSTAN")
            }, {
                "id": 132,
                "code": "LA",
                "name": $L("LAO PEOPLE'S DEMOCRATIC REPUBLIC")
            }, {
                "id": 140,
                "code": "LV",
                "name": $L("LATVIA")
            }, {
                "id": 133,
                "code": "LB",
                "name": $L("LEBANON")
            }, {
                "id": 138,
                "code": "LS",
                "name": $L("LESOTHO")
            }, {
                "id": 137,
                "code": "LR",
                "name": $L("LIBERIA")
            }, {
                "id": 141,
                "code": "LY",
                "name": $L("LIBYAN ARAB JAMAHIRIYA")
            }, {
                "id": 135,
                "code": "LI",
                "name": $L("LIECHTENSTEIN")
            }, {
                "id": 139,
                "code": "LT",
                "name": $L("LITHUANIA")
            }, {
                "id": 14,
                "code": "LU",
                "name": $L("LUXEMBOURG")
            }, {
                "id": 151,
                "code": "MO",
                "name": $L("MACAO")
            }, {
                "id": 145,
                "code": "MG",
                "name": $L("MADAGASCAR")
            }, {
                "id": 159,
                "code": "MW",
                "name": $L("MALAWI")
            }, {
                "id": 27,
                "code": "MY",
                "name": $L("MALAYSIA")
            }, {
                "id": 158,
                "code": "MV",
                "name": $L("MALDIVES")
            }, {
                "id": 148,
                "code": "ML",
                "name": $L("MALI")
            }, {
                "id": 156,
                "code": "MT",
                "name": $L("MALTA")
            }, {
                "id": 146,
                "code": "MH",
                "name": $L("MARSHALL ISLANDS")
            }, {
                "id": 153,
                "code": "MQ",
                "name": $L("MARTINIQUE")
            }, {
                "id": 154,
                "code": "MR",
                "name": $L("MAURITANIA")
            }, {
                "id": 157,
                "code": "MU",
                "name": $L("MAURITIUS")
            }, {
                "id": 234,
                "code": "YT",
                "name": $L("MAYOTTE")
            }, {
                "id": 15,
                "code": "MX",
                "name": $L("MEXICO")
            }, {
                "id": 143,
                "code": "MC",
                "name": $L("MONACO")
            }, {
                "id": 150,
                "code": "MN",
                "name": $L("MONGOLIA")
            }, {
                "id": 242,
                "code": "ME",
                "name": $L("MONTENEGRO")
            }, {
                "id": 155,
                "code": "MS",
                "name": $L("MONTSERRAT")
            }, {
                "id": 142,
                "code": "MA",
                "name": $L("MOROCCO")
            }, {
                "id": 160,
                "code": "MZ",
                "name": $L("MOZAMBIQUE")
            }, {
                "id": 149,
                "code": "MM",
                "name": $L("MYANMAR")
            }, {
                "id": 161,
                "code": "NA",
                "name": $L("NAMIBIA")
            }, {
                "id": 168,
                "code": "NR",
                "name": $L("NAURU")
            }, {
                "id": 167,
                "code": "NP",
                "name": $L("NEPAL")
            }, {
                "id": 16,
                "code": "NL",
                "name": $L("NETHERLANDS")
            }, {
                "id": 40,
                "code": "AN",
                "name": $L("NETHERLANDS ANTILLES")
            }, {
                "id": 162,
                "code": "NC",
                "name": $L("NEW CALEDONIA")
            }, {
                "id": 17,
                "code": "NZ",
                "name": $L("NEW ZEALAND")
            }, {
                "id": 166,
                "code": "NI",
                "name": $L("NICARAGUA")
            }, {
                "id": 163,
                "code": "NE",
                "name": $L("NIGER")
            }, {
                "id": 165,
                "code": "NG",
                "name": $L("NIGERIA")
            }, {
                "id": 169,
                "code": "NU",
                "name": $L("NIUE")
            }, {
                "id": 164,
                "code": "NF",
                "name": $L("NORFOLK ISLAND")
            }, {
                "id": 152,
                "code": "MP",
                "name": $L("NORTHERN MARIANA ISLANDS")
            }, {
                "id": 18,
                "code": "NO",
                "name": $L("NORWAY")
            }, {
                "id": 243,
                "code": "PS",
                "name": $L("OCCUPIED PALESTINIAN TERRITORY")
            }, {
                "id": 170,
                "code": "OM",
                "name": $L("OMAN")
            }, {
                "id": 175,
                "code": "PK",
                "name": $L("PAKISTAN")
            }, {
                "id": 181,
                "code": "PW",
                "name": $L("PALAU")
            }, {
                "id": 171,
                "code": "PA",
                "name": $L("PANAMA")
            }, {
                "id": 174,
                "code": "PG",
                "name": $L("PAPUA NEW GUINEA")
            }, {
                "id": 182,
                "code": "PY",
                "name": $L("PARAGUAY")
            }, {
                "id": 172,
                "code": "PE",
                "name": $L("PERU")
            }, {
                "id": 29,
                "code": "PH",
                "name": $L("PHILIPPINES")
            }, {
                "id": 178,
                "code": "PN",
                "name": $L("PITCAIRN")
            }, {
                "id": 176,
                "code": "PL",
                "name": $L("POLAND")
            }, {
                "id": 180,
                "code": "PT",
                "name": $L("PORTUGAL")
            }, {
                "id": 32,
                "code": "TW",
                "name": $L("TAIWAN")
            }, {
                "id": 179,
                "code": "PR",
                "name": $L("PUERTO RICO")
            }, {
                "id": 183,
                "code": "QA",
                "name": $L("QATAR")
            }, {
                "id": 26,
                "code": "KR",
                "name": $L("REPUBLIC OF KOREA")
            }, {
                "id": 144,
                "code": "MD",
                "name": $L("REPUBLIC OF MOLDOVA")
            }, {
                "id": 184,
                "code": "RE",
                "name": $L("REUNION")
            }, {
                "id": 185,
                "code": "RO",
                "name": $L("ROMANIA")
            }, {
                "id": 186,
                "code": "RU",
                "name": $L("RUSSIAN FEDERATION")
            }, {
                "id": 187,
                "code": "RW",
                "name": $L("RWANDA")
            }, {
                "id": 192,
                "code": "SH",
                "name": $L("SAINT HELENA")
            }, {
                "id": 127,
                "code": "KN",
                "name": $L("SAINT KITTS AND NEVIS")
            }, {
                "id": 134,
                "code": "LC",
                "name": $L("SAINT LUCIA")
            }, {
                "id": 177,
                "code": "PM",
                "name": $L("SAINT PIERRE AND MIQUELON")
            }, {
                "id": 225,
                "code": "VC",
                "name": $L("SAINT VINCENT AND THE GRENADINES")
            }, {
                "id": 232,
                "code": "WS",
                "name": $L("SAMOA")
            }, {
                "id": 197,
                "code": "SM",
                "name": $L("SAN MARINO")
            }, {
                "id": 201,
                "code": "ST",
                "name": $L("SAO TOME AND PRINCIPE")
            }, {
                "id": 188,
                "code": "SA",
                "name": $L("SAUDI ARABIA")
            }, {
                "id": 198,
                "code": "SN",
                "name": $L("SENEGAL")
            }, {
                "id": 244,
                "code": "RS",
                "name": $L("SERBIA")
            }, {
                "id": 190,
                "code": "SC",
                "name": $L("SEYCHELLES")
            }, {
                "id": 196,
                "code": "SL",
                "name": $L("SIERRA LEONE")
            }, {
                "id": 30,
                "code": "SG",
                "name": $L("SINGAPORE")
            }, {
                "id": 195,
                "code": "SK",
                "name": $L("SLOVAKIA")
            }, {
                "id": 193,
                "code": "SI",
                "name": $L("SLOVENIA")
            }, {
                "id": 189,
                "code": "SB",
                "name": $L("SOLOMON ISLANDS")
            }, {
                "id": 199,
                "code": "SO",
                "name": $L("SOMALIA")
            }, {
                "id": 236,
                "code": "ZA",
                "name": $L("SOUTH AFRICA")
            }, {
                "id": 106,
                "code": "GS",
                "name": $L("SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS")
            }, {
                "id": 19,
                "code": "ES",
                "name": $L("SPAIN")
            }, {
                "id": 136,
                "code": "LK",
                "name": $L("SRI LANKA")
            }, {
                "id": 191,
                "code": "SD",
                "name": $L("SUDAN")
            }, {
                "id": 200,
                "code": "SR",
                "name": $L("SURINAME")
            }, {
                "id": 194,
                "code": "SJ",
                "name": $L("SVALBARD AND JAN MAYEN")
            }, {
                "id": 204,
                "code": "SZ",
                "name": $L("SWAZILAND")
            }, {
                "id": 20,
                "code": "SE",
                "name": $L("SWEDEN")
            }, {
                "id": 21,
                "code": "CH",
                "name": $L("SWITZERLAND")
            }, {
                "id": 203,
                "code": "SY",
                "name": $L("SYRIAN ARAB REPUBLIC")
            }, {
                "id": 209,
                "code": "TJ",
                "name": $L("TAJIKISTAN")
            }, {
                "id": 31,
                "code": "TH",
                "name": $L("THAILAND")
            }, {
                "id": 65,
                "code": "CD",
                "name": $L("THE DEMOCRATIC REPUBLIC OF THE CONGO")
            }, {
                "id": 147,
                "code": "MK",
                "name": $L("THE FORMER YUGOSLAV REPUBLIC OF MACEDONIA")
            }, {
                "id": 211,
                "code": "TL",
                "name": $L("TIMOR-LESTE")
            }, {
                "id": 208,
                "code": "TG",
                "name": $L("TOGO")
            }, {
                "id": 210,
                "code": "TK",
                "name": $L("TOKELAU")
            }, {
                "id": 214,
                "code": "TO",
                "name": $L("TONGA")
            }, {
                "id": 216,
                "code": "TT",
                "name": $L("TRINIDAD AND TOBAGO")
            }, {
                "id": 213,
                "code": "TN",
                "name": $L("TUNISIA")
            }, {
                "id": 215,
                "code": "TR",
                "name": $L("TURKEY")
            }, {
                "id": 212,
                "code": "TM",
                "name": $L("TURKMENISTAN")
            }, {
                "id": 205,
                "code": "TC",
                "name": $L("TURKS AND CAICOS ISLANDS")
            }, {
                "id": 217,
                "code": "TV",
                "name": $L("TUVALU")
            }, {
                "id": 228,
                "code": "VI",
                "name": $L("U.S. VIRGIN ISLANDS")
            }, {
                "id": 220,
                "code": "UG",
                "name": $L("UGANDA")
            }, {
                "id": 219,
                "code": "UA",
                "name": $L("UKRAINE")
            }, {
                "id": 34,
                "code": "AE",
                "name": $L("UNITED ARAB EMIRATES")
            }, {
                "id": 22,
                "code": "GB",
                "name": $L("UNITED KINGDOM")
            }, {
                "id": 218,
                "code": "TZ",
                "name": $L("UNITED REPUBLIC OF TANZANIA")
            }, {
                "id": 23,
                "code": "US",
                "name": $L("UNITED STATES")
            }, {
                "id": 221,
                "code": "UM",
                "name": $L("UNITED STATES MINOR OUTLYING ISLANDS")
            }, {
                "id": 222,
                "code": "UY",
                "name": $L("URUGUAY")
            }, {
                "id": 223,
                "code": "UZ",
                "name": $L("UZBEKISTAN")
            }, {
                "id": 230,
                "code": "VU",
                "name": $L("VANUATU")
            }, {
                "id": 226,
                "code": "VE",
                "name": $L("VENEZUELA")
            }, {
                "id": 229,
                "code": "VN",
                "name": $L("VIET NAM")
            }, {
                "id": 231,
                "code": "WF",
                "name": $L("WALLIS AND FUTUNA")
            }, {
                "id": 86,
                "code": "EH",
                "name": $L("WESTERN SAHARA")
            }, {
                "id": 233,
                "code": "YE",
                "name": $L("YEMEN")
            }, {
                "id": 237,
                "code": "ZM",
                "name": $L("ZAMBIA")
            }, {
                "id": 238,
                "code": "ZW",
                "name": $L("ZIMBABWE")
            }]
        }
    }
}
